[project]
name = "controller"
version = "0.1.0"
description = "P4 Container Flow Controller for Tofino2"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "flask>=3.0.3",
    "grpcio>=1.66.1",
    "protobuf>=5.28.0",
    "scapy>=2.5.0",
]
